### ISSUE TITLE
Im trying to create colab file but when I run train.py I get this error which i dont get on my machine

### ISSUE THREAD

**Issue by archmord** [andabi/music-source-separation#33]
`Traceback (most recent call last):
  File "train.py", line 98, in <module>
    train()
  File "train.py", line 47, in train
    mixed_wav, src1_wav, src2_wav, _ = data.next_wavs(TrainConfig.SECONDS, TrainConfig.NUM_WAVFILE)
  File "/content/music-source-separation/data.py", line 22, in next_wavs
    wavfiles = random.sample(wavfiles, size)
  File "/usr/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative`

**Comment by appernetic** [comment]
Oracle Filtering!
https://colab.research.google.com/drive/1Zo6iSPIi6SjOAL7wg8yzVWkS9mjLgjI-
